USE [master]
GO

/****** Object:  Database [LoanStarMessageBusBroker]    Script Date: 1/13/2020 2:23:59 PM ******/
DROP DATABASE [LoanStarMessageBusBroker]
GO

/****** Object:  Database [LoanStarMessageBusBroker]    Script Date: 1/13/2020 2:23:59 PM ******/
CREATE DATABASE [LoanStarMessageBusBroker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoanStarMessageBusBroker', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.ALVIANDA\MSSQL\DATA\LoanStarMessageBusBroker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LoanStarMessageBusBroker_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.ALVIANDA\MSSQL\DATA\LoanStarMessageBusBroker_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoanStarMessageBusBroker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET RECOVERY FULL 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET  MULTI_USER 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LoanStarMessageBusBroker] SET  READ_WRITE 
GO


