USE [master]
GO

/****** Object:  Database [AlviandaMessageBroker]    Script Date: 1/13/2020 2:23:59 PM ******/
DROP DATABASE IF EXISTS [AlviandaMessageBroker]
GO

/****** Object:  Database [AlviandaMessageBroker]    Script Date: 1/13/2020 2:23:59 PM ******/
CREATE DATABASE [AlviandaMessageBusBroker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlviandaMessageBroker', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AlviandaMessageBroker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AlviandaMessageBroker_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AlviandaMessageBroker_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AlviandaMessageBroker] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlviandaMessageBroker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlviandaMessageBroker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlviandaMessageBroker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlviandaMessageBroker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AlviandaMessageBroker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlviandaMessageBroker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET RECOVERY FULL 
GO

ALTER DATABASE [AlviandaMessageBroker] SET  MULTI_USER 
GO

ALTER DATABASE [AlviandaMessageBroker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlviandaMessageBroker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlviandaMessageBroker] SET FILESTREAM ( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlviandaMessageBroker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AlviandaMessageBroker] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AlviandaMessageBroker] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AlviandaMessageBroker] SET  READ_WRITE 
GO

