USE [AlviandaMessageBroker]

CREATE SERVICE DateTimeInitiatorService
ON QUEUE DateTimeInitiatorQueue 
(
[mhb.cbs.DateTimeContract]
)
GO
CREATE SERVICE DateTimeTargetService
ON QUEUE DateTimeTargetQueue
(
[mhb.cbs.DateTimeContract]
)
GO

/** following set of services are generated by running the below queries **/
/** SELECT DISTINCT 'CREATE SERVICE '+ServiceConsumer+' ON QUEUE '+QueueConsumer+' (['+Contract+'])' FROM [AlviandaMessageBroker].[dbo].[BrokerServicesMatrix] **/

CREATE SERVICE ServiceConsumerA0 ON QUEUE dbo.QueueConsumerA ([mhb.cbs.ContractInType0])
CREATE SERVICE ServiceConsumerA2 ON QUEUE dbo.QueueConsumerA ([mhb.cbs.ContractInType2])
CREATE SERVICE ServiceConsumerA3 ON QUEUE dbo.QueueConsumerA ([mhb.cbs.ContractInType3])
CREATE SERVICE ServiceConsumerB0 ON QUEUE dbo.QueueConsumerB ([mhb.cbs.ContractInType0])
CREATE SERVICE ServiceConsumerB1 ON QUEUE dbo.QueueConsumerB ([mhb.cbs.ContractInType1])
CREATE SERVICE ServiceConsumerB2 ON QUEUE dbo.QueueConsumerB ([mhb.cbs.ContractInType2])
CREATE SERVICE ServiceConsumerB3 ON QUEUE dbo.QueueConsumerB ([mhb.cbs.ContractInType3])
CREATE SERVICE ServiceConsumerC1 ON QUEUE dbo.QueueConsumerC ([mhb.cbs.ContractInType1])
CREATE SERVICE ServiceConsumerC3 ON QUEUE dbo.QueueConsumerC ([mhb.cbs.ContractInType3])
CREATE SERVICE ServiceConsumerC4 ON QUEUE dbo.QueueConsumerC ([mhb.cbs.ContractInType4])
CREATE SERVICE ServiceConsumerD1 ON QUEUE dbo.QueueConsumerD ([mhb.cbs.ContractInType1])
CREATE SERVICE ServiceConsumerD4 ON QUEUE dbo.QueueConsumerD ([mhb.cbs.ContractInType4])
CREATE SERVICE ServiceConsumerE0 ON QUEUE dbo.QueueConsumerE ([mhb.cbs.ContractInType0])
CREATE SERVICE ServiceConsumerE2 ON QUEUE dbo.QueueConsumerE ([mhb.cbs.ContractInType2])
CREATE SERVICE ServiceConsumerE4 ON QUEUE dbo.QueueConsumerE ([mhb.cbs.ContractInType4])
GO
